In [3]:
import pandas as pd
import zipfile
from transliterate import translit

In [46]:
path_to_train = '../data/df_train_with_poi.zip'
zip_file = zipfile.ZipFile(path_to_train)
train_df = pd.read_csv(zip_file.open(zip_file.namelist()[0]))

/home/alitvintsev/env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [47]:
train_df.columns

Index(['Unnamed: 0', 'city', 'floor', 'id', 'lat', 'lng',
       'osm_amenity_points_in_0.001', 'osm_amenity_points_in_0.005',
       'osm_amenity_points_in_0.0075', 'osm_amenity_points_in_0.01',
       ...
       'poi_n_bus_stop_r0.002', 'poi_n_cafe_r0.002',
       'poi_n_supermarket_r0.002', 'poi_n_atm_r0.002', 'poi_n_bank_r0.002',
       'poi_n_clothes_r0.002', 'poi_n_fast_food_r0.002',
       'poi_n_hairdresser_r0.002', 'poi_n_restaurant_r0.002',
       'poi_n_tram_stop_r0.002'],
      dtype='object', length=130)

In [48]:
train_df = train_df.drop(columns=['Unnamed: 0'])

In [49]:
train_df.head()

,city,floor,id,lat,lng,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,...,poi_n_bus_stop_r0.002,poi_n_cafe_r0.002,poi_n_supermarket_r0.002,poi_n_atm_r0.002,poi_n_bank_r0.002,poi_n_clothes_r0.002,poi_n_fast_food_r0.002,poi_n_hairdresser_r0.002,poi_n_restaurant_r0.002,poi_n_tram_stop_r0.002
0,Пермь,NaN,COL_0,57.998207,56.292797,4,19,35,52,0,...,0,0,0,0,0,0,0,0,0,0
1,Шатура,NaN,COL_1,55.574284,39.543835,3,24,37,59,0,...,0,0,0,0,0,0,0,0,0,0
2,Ярославль,NaN,COL_2,57.619140,39.850525,1,30,67,128,0,...,0,0,0,0,0,0,0,0,0,0
3,Новокузнецк,NaN,COL_3,53.897083,87.108604,0,0,5,21,0,...,0,0,0,0,0,0,0,0,0,0
4,Москва,NaN,COL_4,55.802590,37.487110,1,23,64,153,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
poi_cols = [
    'poi_n_r0.001',
    'poi_n_bus_stop_r0.001',
    'poi_n_cafe_r0.001',
    'poi_n_supermarket_r0.001',
    'poi_n_atm_r0.001',
    'poi_n_bank_r0.001',
    'poi_n_clothes_r0.001',
    'poi_n_fast_food_r0.001',
    'poi_n_hairdresser_r0.001',
    'poi_n_restaurant_r0.001',
    'poi_n_tram_stop_r0.001',
    'poi_n_Сбербанк',
    'poi_closest_Сбербанк',
    'poi_n_Пятёрочка',
    'poi_closest_Пятёрочка',
    'poi_n_Магнит',
    'poi_closest_Магнит',
    'poi_n_DNS',
    'poi_closest_DNS',
    'poi_n_Дикси',
    'poi_closest_Дикси',
    'poi_n_Красное & Белое',
    'poi_closest_Красное & Белое',
    'poi_n_Красное&Белое',
    'poi_closest_Красное&Белое',
    'poi_n_МТС',
    'poi_closest_МТС',
    'poi_n_ВТБ',
    'poi_closest_ВТБ',
    'poi_n_Coffee Like',
    'poi_closest_Coffee Like',
    'poi_n_Столовая',
    'poi_closest_Столовая',
    'poi_n_Связной',
    'poi_closest_Связной',
    'poi_n_Бристоль',
    'poi_closest_Бристоль',
    'poi_n_Бургер Кинг',
    'poi_closest_Бургер Кинг',
    'poi_n_Альфа-Банк',
    'poi_closest_Альфа-Банк',
    'poi_n_r0.002',
    'poi_n_bus_stop_r0.002',
    'poi_n_cafe_r0.002',
    'poi_n_supermarket_r0.002',
    'poi_n_atm_r0.002',
    'poi_n_bank_r0.002',
    'poi_n_clothes_r0.002',
    'poi_n_fast_food_r0.002',
    'poi_n_hairdresser_r0.002',
    'poi_n_restaurant_r0.002',
    'poi_n_tram_stop_r0.002'
]

In [51]:
poi_cols_to_rename = [
    'poi_n_Сбербанк',
    'poi_closest_Сбербанк',
    'poi_n_Пятёрочка',
    'poi_closest_Пятёрочка',
    'poi_n_Магнит',
    'poi_closest_Магнит',
    'poi_n_Дикси',
    'poi_closest_Дикси',
    'poi_n_Красное & Белое',
    'poi_closest_Красное & Белое',
    'poi_n_Красное&Белое',
    'poi_closest_Красное&Белое',
    'poi_n_МТС',
    'poi_closest_МТС',
    'poi_n_ВТБ',
    'poi_closest_ВТБ',
    'poi_n_Столовая',
    'poi_closest_Столовая',
    'poi_n_Связной',
    'poi_closest_Связной',
    'poi_n_Бристоль',
    'poi_closest_Бристоль',
    'poi_n_Бургер Кинг',
    'poi_closest_Бургер Кинг',
    'poi_n_Альфа-Банк',
    'poi_closest_Альфа-Банк',
]

In [52]:
cols_to_rename = {}
for column in poi_cols:
    try:
        cols_to_rename[column] = translit(column, reversed=True).replace(' ', '_').replace("'", "").replace('&', '')
    except:
        cols_to_rename[column] = column.replace(' ', '_')

In [53]:
cols_to_rename

{'poi_n_r0.001': 'poi_n_r0.001',
 'poi_n_bus_stop_r0.001': 'poi_n_bus_stop_r0.001',
 'poi_n_cafe_r0.001': 'poi_n_cafe_r0.001',
 'poi_n_supermarket_r0.001': 'poi_n_supermarket_r0.001',
 'poi_n_atm_r0.001': 'poi_n_atm_r0.001',
 'poi_n_bank_r0.001': 'poi_n_bank_r0.001',
 'poi_n_clothes_r0.001': 'poi_n_clothes_r0.001',
 'poi_n_fast_food_r0.001': 'poi_n_fast_food_r0.001',
 'poi_n_hairdresser_r0.001': 'poi_n_hairdresser_r0.001',
 'poi_n_restaurant_r0.001': 'poi_n_restaurant_r0.001',
 'poi_n_tram_stop_r0.001': 'poi_n_tram_stop_r0.001',
 'poi_n_Сбербанк': 'poi_n_Sberbank',
 'poi_closest_Сбербанк': 'poi_closest_Sberbank',
 'poi_n_Пятёрочка': 'poi_n_Pjaterochka',
 'poi_closest_Пятёрочка': 'poi_closest_Pjaterochka',
 'poi_n_Магнит': 'poi_n_Magnit',
 'poi_closest_Магнит': 'poi_closest_Magnit',
 'poi_n_DNS': 'poi_n_DNS',
 'poi_closest_DNS': 'poi_closest_DNS',
 'poi_n_Дикси': 'poi_n_Diksi',
 'poi_closest_Дикси': 'poi_closest_Diksi',
 'poi_n_Красное & Белое': 'poi_n_Krasnoe__Beloe',
 'poi_closest_Красное & Белое': 'poi_closest_Krasnoe__Beloe',
 'poi_n_Красное&Белое': 'poi_n_KrasnoeBeloe',
 'poi_closest_Красное&Белое': 'poi_closest_KrasnoeBeloe',
 'poi_n_МТС': 'poi_n_MTS',
 'poi_closest_МТС': 'poi_closest_MTS',
 'poi_n_ВТБ': 'poi_n_VTB',
 'poi_closest_ВТБ': 'poi_closest_VTB',
 'poi_n_Coffee Like': 'poi_n_Coffee_Like',
 'poi_closest_Coffee Like': 'poi_closest_Coffee_Like',
 'poi_n_Столовая': 'poi_n_Stolovaja',
 'poi_closest_Столовая': 'poi_closest_Stolovaja',
 'poi_n_Связной': 'poi_n_Svjaznoj',
 'poi_closest_Связной': 'poi_closest_Svjaznoj',
 'poi_n_Бристоль': 'poi_n_Bristol',
 'poi_closest_Бристоль': 'poi_closest_Bristol',
 'poi_n_Бургер Кинг': 'poi_n_Burger_King',
 'poi_closest_Бургер Кинг': 'poi_closest_Burger_King',
 'poi_n_Альфа-Банк': 'poi_n_Alfa-Bank',
 'poi_closest_Альфа-Банк': 'poi_closest_Alfa-Bank',
 'poi_n_r0.002': 'poi_n_r0.002',
 'poi_n_bus_stop_r0.002': 'poi_n_bus_stop_r0.002',
 'poi_n_cafe_r0.002': 'poi_n_cafe_r0.002',
 'poi_n_supermarket_r0.002': 'poi_n_supermarket_r0.002',
 'poi_n_atm_r0.002': 'poi_n_atm_r0.002',
 'poi_n_bank_r0.002': 'poi_n_bank_r0.002',
 'poi_n_clothes_r0.002': 'poi_n_clothes_r0.002',
 'poi_n_fast_food_r0.002': 'poi_n_fast_food_r0.002',
 'poi_n_hairdresser_r0.002': 'poi_n_hairdresser_r0.002',
 'poi_n_restaurant_r0.002': 'poi_n_restaurant_r0.002',
 'poi_n_tram_stop_r0.002': 'poi_n_tram_stop_r0.002'}

In [54]:
train_df = train_df.rename(columns=cols_to_rename)

In [55]:
train_df.head()

,city,floor,id,lat,lng,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,...,poi_n_bus_stop_r0.002,poi_n_cafe_r0.002,poi_n_supermarket_r0.002,poi_n_atm_r0.002,poi_n_bank_r0.002,poi_n_clothes_r0.002,poi_n_fast_food_r0.002,poi_n_hairdresser_r0.002,poi_n_restaurant_r0.002,poi_n_tram_stop_r0.002
0,Пермь,NaN,COL_0,57.998207,56.292797,4,19,35,52,0,...,0,0,0,0,0,0,0,0,0,0
1,Шатура,NaN,COL_1,55.574284,39.543835,3,24,37,59,0,...,0,0,0,0,0,0,0,0,0,0
2,Ярославль,NaN,COL_2,57.619140,39.850525,1,30,67,128,0,...,0,0,0,0,0,0,0,0,0,0
3,Новокузнецк,NaN,COL_3,53.897083,87.108604,0,0,5,21,0,...,0,0,0,0,0,0,0,0,0,0
4,Москва,NaN,COL_4,55.802590,37.487110,1,23,64,153,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
train_df.to_csv('../data/df_train_with_poi_lat.csv', compression='zip')

In [57]:
path_to_test = '../data/df_test_with_poi.zip'
zip_file = zipfile.ZipFile(path_to_test)
test_df = pd.read_csv(zip_file.open(zip_file.namelist()[0]))

In [58]:
test_df = test_df.rename(columns=cols_to_rename)

In [59]:
test_df.to_csv('../data/df_test_with_poi_lat.csv', compression='zip')

In [5]:
train_df = pd.read_csv('../data/df_train_with_poi_lat.csv', compression='zip')

/home/alitvintsev/env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [10]:
train_df.columns[69]

'reform_mean_floor_count_500'

In [60]:
for i in train_df.columns:
    print(i)

city
floor
id
lat
lng
osm_amenity_points_in_0.001
osm_amenity_points_in_0.005
osm_amenity_points_in_0.0075
osm_amenity_points_in_0.01
osm_building_points_in_0.001
osm_building_points_in_0.005
osm_building_points_in_0.0075
osm_building_points_in_0.01
osm_catering_points_in_0.001
osm_catering_points_in_0.005
osm_catering_points_in_0.0075
osm_catering_points_in_0.01
osm_city_closest_dist
osm_city_nearest_name
osm_city_nearest_population
osm_crossing_closest_dist
osm_crossing_points_in_0.001
osm_crossing_points_in_0.005
osm_crossing_points_in_0.0075
osm_crossing_points_in_0.01
osm_culture_points_in_0.001
osm_culture_points_in_0.005
osm_culture_points_in_0.0075
osm_culture_points_in_0.01
osm_finance_points_in_0.001
osm_finance_points_in_0.005
osm_finance_points_in_0.0075
osm_finance_points_in_0.01
osm_healthcare_points_in_0.005
osm_healthcare_points_in_0.0075
osm_healthcare_points_in_0.01
osm_historic_points_in_0.005
osm_historic_points_in_0.0075
osm_historic_points_in_0.01
osm_hotels_points_in_0.005
osm_hotels_points_in_0.0075
osm_hotels_points_in_0.01
osm_leisure_points_in_0.005
osm_leisure_points_in_0.0075
osm_leisure_points_in_0.01
osm_offices_points_in_0.001
osm_offices_points_in_0.005
osm_offices_points_in_0.0075
osm_offices_points_in_0.01
osm_shops_points_in_0.001
osm_shops_points_in_0.005
osm_shops_points_in_0.0075
osm_shops_points_in_0.01
osm_subway_closest_dist
osm_train_stop_closest_dist
osm_train_stop_points_in_0.005
osm_train_stop_points_in_0.0075
osm_train_stop_points_in_0.01
osm_transport_stop_closest_dist
osm_transport_stop_points_in_0.005
osm_transport_stop_points_in_0.0075
osm_transport_stop_points_in_0.01
per_square_meter_price
reform_count_of_houses_1000
reform_count_of_houses_500
reform_house_population_1000
reform_house_population_500
reform_mean_floor_count_1000
reform_mean_floor_count_500
reform_mean_year_building_1000
reform_mean_year_building_500
region
total_square
street
date
realty_type
price_type
poi_n_r0.001
poi_n_bus_stop_r0.001
poi_n_cafe_r0.001
poi_n_supermarket_r0.001
poi_n_atm_r0.001
poi_n_bank_r0.001
poi_n_clothes_r0.001
poi_n_fast_food_r0.001
poi_n_hairdresser_r0.001
poi_n_restaurant_r0.001
poi_n_tram_stop_r0.001
poi_n_Sberbank
poi_closest_Sberbank
poi_n_Pjaterochka
poi_closest_Pjaterochka
poi_n_Magnit
poi_closest_Magnit
poi_n_DNS
poi_closest_DNS
poi_n_Diksi
poi_closest_Diksi
poi_n_Krasnoe__Beloe
poi_closest_Krasnoe__Beloe
poi_n_KrasnoeBeloe
poi_closest_KrasnoeBeloe
poi_n_MTS
poi_closest_MTS
poi_n_VTB
poi_closest_VTB
poi_n_Coffee_Like
poi_closest_Coffee_Like
poi_n_Stolovaja
poi_closest_Stolovaja
poi_n_Svjaznoj
poi_closest_Svjaznoj
poi_n_Bristol
poi_closest_Bristol
poi_n_Burger_King
poi_closest_Burger_King
poi_n_Alfa-Bank
poi_closest_Alfa-Bank
poi_n_r0.002
poi_n_bus_stop_r0.002
poi_n_cafe_r0.002
poi_n_supermarket_r0.002
poi_n_atm_r0.002
poi_n_bank_r0.002
poi_n_clothes_r0.002
poi_n_fast_food_r0.002
poi_n_hairdresser_r0.002
poi_n_restaurant_r0.002
poi_n_tram_stop_r0.002